NAME = convert
SRC = main.cpp ScalarConverter.cpp
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(NAME)

clean:
	#

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
